# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83b9fe38a171b9bab1f727ad0898c4a6320771f6eaa3dd25ec950283c1e8d9656eeb7d5ca182cf6849fe4a0d1f02084060d322b73e043ddbe9268d3a38a36738

test:
  secret_key_base: ddecec3da7202fbbee445f94ffe27e5c2d969c001c29322df8922e0d320ddbe159aa227bfd1a2344a4961d9093290ce91af72198a6af5f69815eddbdd0bc47c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
